travis:
  secure:
    BINSTAR_TOKEN: mqvMqOMXyygXD6U2Kgy+lsmhEKNktHRTSa5/gcyieoGllWO7DQhxNXTpnAZ9ODQvir21mD3R349AUsjq4PdrKgttTklqcnov4SUVoo9kQC9qxe9BMzbHb3PW1Kubnw+aXnXIo39mZwmhW5n3JMrwMEFcwn+mQ+wasF1JpwbuM5wXe1BHTxmat6y0yOSb5TjlckA4Yv3oJujcsP6NbEbwzf7ay1leW+StbcaVESN7JIMLId+yKbHrY3pkOGkDeIQDYxTdwT5r0OcI013J5HaFho/Fh31cjSi8U58PgsMwvm43ABnZE8cA0e4ITlfd15kP1JxSnxZHmVSjeEc//ysflQG6vRTz1wEutgNMEqs59wX6d5+0OML4JuwM2ys3JpgEelLPjlBDtTvRUl45yjXuvpCwMP1oDkqeIx6pJ4CAufUhfJiTZpL7uL2btmTD2AzZmNr7qyzNFzfc4dUmVtSYdiOIhgyUx6rv+q4JBtlUAB0MaE2X6sBqas5UgKs+boRnXUihKlpphPWzjc4iUwfujMDlbURA3S7KLSR8qu+TMmOtH91d1l0jAhNoiXyxU8gGPR5HeiqQLeIA+y0U6dQobQA/JT1an8eW/4+/k7lxwNTarhXilAMQpOPnRu4DxQZTX9A+jhA9Gaa4HRU91h5f0wYMDeuiV3OxwzA/xCzlyig=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
